// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: remote_exec.proto

package tipb

import (
	"fmt"
	"io"
	"math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"

	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RemoteExecPlan is the tree-only plan used by RemoteExecutor.
//
// It explicitly carries the minimal session fields required during execution
// (extracted from DAGRequest) to avoid inheriting full DAG semantics.
type RemoteExecPlan struct {
	// Tree-only executor plan.
	RootExecutor *Executor `protobuf:"bytes,1,opt,name=root_executor,json=rootExecutor" json:"root_executor,omitempty"`
	// Session fields required by RemoteExecutor.
	TimeZoneName          string  `protobuf:"bytes,2,opt,name=time_zone_name,json=timeZoneName" json:"time_zone_name"`
	TimeZoneOffset        int64   `protobuf:"varint,3,opt,name=time_zone_offset,json=timeZoneOffset" json:"time_zone_offset"`
	Flags                 uint64  `protobuf:"varint,4,opt,name=flags" json:"flags"`
	SqlMode               *uint64 `protobuf:"varint,5,opt,name=sql_mode,json=sqlMode" json:"sql_mode,omitempty"`
	MaxWarningCount       *uint64 `protobuf:"varint,6,opt,name=max_warning_count,json=maxWarningCount" json:"max_warning_count,omitempty"`
	DivPrecisionIncrement *uint32 `protobuf:"varint,7,opt,name=div_precision_increment,json=divPrecisionIncrement" json:"div_precision_increment,omitempty"`
}

func (m *RemoteExecPlan) Reset()         { *m = RemoteExecPlan{} }
func (m *RemoteExecPlan) String() string { return proto.CompactTextString(m) }
func (*RemoteExecPlan) ProtoMessage()    {}
func (*RemoteExecPlan) Descriptor() ([]byte, []int) {
	return fileDescriptor_8351eb49c8e19de0, []int{0}
}
func (m *RemoteExecPlan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoteExecPlan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoteExecPlan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoteExecPlan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteExecPlan.Merge(m, src)
}
func (m *RemoteExecPlan) XXX_Size() int {
	return m.Size()
}
func (m *RemoteExecPlan) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteExecPlan.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteExecPlan proto.InternalMessageInfo

func (m *RemoteExecPlan) GetRootExecutor() *Executor {
	if m != nil {
		return m.RootExecutor
	}
	return nil
}

func (m *RemoteExecPlan) GetTimeZoneName() string {
	if m != nil {
		return m.TimeZoneName
	}
	return ""
}

func (m *RemoteExecPlan) GetTimeZoneOffset() int64 {
	if m != nil {
		return m.TimeZoneOffset
	}
	return 0
}

func (m *RemoteExecPlan) GetFlags() uint64 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *RemoteExecPlan) GetSqlMode() uint64 {
	if m != nil && m.SqlMode != nil {
		return *m.SqlMode
	}
	return 0
}

func (m *RemoteExecPlan) GetMaxWarningCount() uint64 {
	if m != nil && m.MaxWarningCount != nil {
		return *m.MaxWarningCount
	}
	return 0
}

func (m *RemoteExecPlan) GetDivPrecisionIncrement() uint32 {
	if m != nil && m.DivPrecisionIncrement != nil {
		return *m.DivPrecisionIncrement
	}
	return 0
}

func init() {
	proto.RegisterType((*RemoteExecPlan)(nil), "tipb.RemoteExecPlan")
}

func init() { proto.RegisterFile("remote_exec.proto", fileDescriptor_8351eb49c8e19de0) }

var fileDescriptor_8351eb49c8e19de0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0x87, 0x33, 0xbb, 0x59, 0x77, 0x1d, 0x77, 0xb3, 0x76, 0xb0, 0x18, 0x7b, 0x88, 0xc1, 0x53,
	0xe8, 0x21, 0x82, 0x82, 0xe0, 0xb5, 0xd2, 0x83, 0x07, 0xb5, 0xe4, 0x22, 0x78, 0x19, 0xa6, 0xc9,
	0xdb, 0x30, 0x90, 0x99, 0x37, 0x9d, 0x4c, 0x6b, 0xf0, 0x53, 0x78, 0xf4, 0x23, 0xf8, 0x21, 0xfc,
	0x00, 0x3d, 0xf6, 0xd8, 0x93, 0x48, 0xf3, 0x45, 0x24, 0xff, 0xd8, 0xdb, 0x2f, 0xcf, 0xf3, 0xf0,
	0x06, 0x86, 0x4e, 0x0c, 0x28, 0xb4, 0xc0, 0xa1, 0x86, 0x34, 0x2e, 0x0d, 0x5a, 0x64, 0xae, 0x95,
	0xe5, 0x7a, 0xe6, 0xb5, 0x64, 0x67, 0xd1, 0xf4, 0x74, 0xf6, 0x2c, 0xc7, 0x1c, 0xbb, 0xf9, 0xba,
	0x5d, 0x03, 0xbd, 0x37, 0xbb, 0xca, 0x76, 0xb3, 0x07, 0xaf, 0xfe, 0x5c, 0x50, 0x2f, 0xe9, 0x4e,
	0x2e, 0x6b, 0x48, 0x57, 0x85, 0xd0, 0xec, 0x2d, 0xbd, 0x33, 0x88, 0x96, 0x8f, 0x07, 0x7d, 0x12,
	0x92, 0xe8, 0xc9, 0x1b, 0x2f, 0x6e, 0xff, 0x13, 0x2f, 0x07, 0x9a, 0xdc, 0xb6, 0xd1, 0xf8, 0xc5,
	0xe6, 0xd4, 0xb3, 0x52, 0x01, 0xff, 0x81, 0x1a, 0xb8, 0x16, 0x0a, 0xfc, 0x8b, 0x90, 0x44, 0x8f,
	0x17, 0xee, 0xe1, 0xef, 0x4b, 0x27, 0xb9, 0x6d, 0xdd, 0x37, 0xd4, 0xf0, 0x59, 0x28, 0x60, 0x31,
	0x7d, 0xfa, 0xd0, 0xe2, 0x66, 0x53, 0x81, 0xf5, 0x2f, 0x43, 0x12, 0x5d, 0x0e, 0xb5, 0x37, 0xd6,
	0x5f, 0x3a, 0xc7, 0x66, 0xf4, 0x6a, 0x53, 0x88, 0xbc, 0xf2, 0xdd, 0x90, 0x44, 0xee, 0x10, 0xf5,
	0x88, 0xbd, 0xa0, 0x37, 0xd5, 0xb6, 0xe0, 0x0a, 0x33, 0xf0, 0xaf, 0x5a, 0x9d, 0x5c, 0x57, 0xdb,
	0xe2, 0x13, 0x66, 0xc0, 0xe6, 0x74, 0xa2, 0x44, 0xcd, 0xbf, 0x0b, 0xa3, 0xa5, 0xce, 0x79, 0x8a,
	0x3b, 0x6d, 0xfd, 0x47, 0x5d, 0x73, 0xaf, 0x44, 0xfd, 0xb5, 0xe7, 0x1f, 0x5a, 0xcc, 0xde, 0xd1,
	0xe7, 0x99, 0xdc, 0xf3, 0xd2, 0x40, 0x2a, 0x2b, 0x89, 0x9a, 0x4b, 0x9d, 0x1a, 0x50, 0xa0, 0xad,
	0x7f, 0x1d, 0x92, 0xe8, 0x2e, 0x99, 0x66, 0x72, 0xbf, 0x1a, 0xed, 0xc7, 0x51, 0x2e, 0xde, 0x9f,
	0x7e, 0xdf, 0x90, 0xc3, 0x39, 0x20, 0xc7, 0x73, 0x40, 0xfe, 0x9d, 0x03, 0xf2, 0xb3, 0x09, 0x9c,
	0x5f, 0x4d, 0xe0, 0x1c, 0x9b, 0xc0, 0x39, 0x35, 0x81, 0x43, 0xa7, 0x29, 0xaa, 0xb8, 0x94, 0x3a,
	0x4f, 0x45, 0x19, 0x5b, 0x99, 0xad, 0xbb, 0x67, 0x5c, 0x91, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x8b, 0x26, 0x00, 0x0c, 0xca, 0x01, 0x00, 0x00,
}

func (m *RemoteExecPlan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoteExecPlan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoteExecPlan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DivPrecisionIncrement != nil {
		i = encodeVarintRemoteExec(dAtA, i, uint64(*m.DivPrecisionIncrement))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxWarningCount != nil {
		i = encodeVarintRemoteExec(dAtA, i, uint64(*m.MaxWarningCount))
		i--
		dAtA[i] = 0x30
	}
	if m.SqlMode != nil {
		i = encodeVarintRemoteExec(dAtA, i, uint64(*m.SqlMode))
		i--
		dAtA[i] = 0x28
	}
	i = encodeVarintRemoteExec(dAtA, i, uint64(m.Flags))
	i--
	dAtA[i] = 0x20
	i = encodeVarintRemoteExec(dAtA, i, uint64(m.TimeZoneOffset))
	i--
	dAtA[i] = 0x18
	i -= len(m.TimeZoneName)
	copy(dAtA[i:], m.TimeZoneName)
	i = encodeVarintRemoteExec(dAtA, i, uint64(len(m.TimeZoneName)))
	i--
	dAtA[i] = 0x12
	if m.RootExecutor != nil {
		{
			size, err := m.RootExecutor.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRemoteExec(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRemoteExec(dAtA []byte, offset int, v uint64) int {
	offset -= sovRemoteExec(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RemoteExecPlan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RootExecutor != nil {
		l = m.RootExecutor.Size()
		n += 1 + l + sovRemoteExec(uint64(l))
	}
	l = len(m.TimeZoneName)
	n += 1 + l + sovRemoteExec(uint64(l))
	n += 1 + sovRemoteExec(uint64(m.TimeZoneOffset))
	n += 1 + sovRemoteExec(uint64(m.Flags))
	if m.SqlMode != nil {
		n += 1 + sovRemoteExec(uint64(*m.SqlMode))
	}
	if m.MaxWarningCount != nil {
		n += 1 + sovRemoteExec(uint64(*m.MaxWarningCount))
	}
	if m.DivPrecisionIncrement != nil {
		n += 1 + sovRemoteExec(uint64(*m.DivPrecisionIncrement))
	}
	return n
}

func sovRemoteExec(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRemoteExec(x uint64) (n int) {
	return sovRemoteExec(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RemoteExecPlan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRemoteExec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoteExecPlan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoteExecPlan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootExecutor", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRemoteExec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRemoteExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RootExecutor == nil {
				m.RootExecutor = &Executor{}
			}
			if err := m.RootExecutor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeZoneName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRemoteExec
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRemoteExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeZoneName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeZoneOffset", wireType)
			}
			m.TimeZoneOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeZoneOffset |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Flags", wireType)
			}
			m.Flags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Flags |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SqlMode", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SqlMode = &v
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWarningCount", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MaxWarningCount = &v
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DivPrecisionIncrement", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DivPrecisionIncrement = &v
		default:
			iNdEx = preIndex
			skippy, err := skipRemoteExec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRemoteExec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRemoteExec(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRemoteExec
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRemoteExec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRemoteExec
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRemoteExec
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRemoteExec
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRemoteExec        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRemoteExec          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRemoteExec = fmt.Errorf("proto: unexpected end of group")
)
